using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public class Dice : MonoBehaviour
{
    [Header("Settle Detection")]
    [SerializeField] private float linearSleepThreshold = 0.05f;
    [SerializeField] private float angularSleepThreshold = 0.05f;
    [SerializeField] private float settleTimeRequired = 0.35f;

    [Header("Gravity")]
    [Tooltip("If enabled, sets Physics.gravity at runtime.")]
    [SerializeField] private bool overrideGlobalGravity = false;
    [SerializeField] private Vector3 customGravity = new Vector3(0f, 0f, 9.81f);

    [Header("Auto Face Generation (Editor)")]
    [SerializeField] private Transform meshRoot;
    [SerializeField] private Transform facesRoot;
    [SerializeField, Range(0.90f, 0.9999f)] private float normalDotThreshold = 0.985f;
    [SerializeField] private bool clearExistingFaces = true;

    private Rigidbody rb;
    private readonly List<DieFace> faces = new List<DieFace>();
    private float settledTimer;

    /// <summary>
    /// Called when the object is spawned, sets up the gravity and face cache
    /// </summary>
    private void Awake()
    {
        if (overrideGlobalGravity)
        {
            Physics.gravity = customGravity;
        }

        rb = GetComponent<Rigidbody>()
             ?? GetComponentInChildren<Rigidbody>(true)
             ?? GetComponentInParent<Rigidbody>();

        if (rb == null)
        {
            Debug.LogError($"[{nameof(Dice)}] No Rigidbody found on {name} (self/children/parent).");
        }

        RebuildFaceCache();
    }

    /// <summary>
    /// Rebuilds the face cache by getting all DieFace components in children
    /// </summary>
    public void RebuildFaceCache()
    {
        faces.Clear();
        faces.AddRange(GetComponentsInChildren<DieFace>(true));
    }

    /// <summary>
    /// Resets the settle state timer
    /// </summary>
    public void ResetSettleState()
    {
        settledTimer = 0f;
    }

    /// <summary>
    /// Checks if the die is settled by checking if the linear and angular velocities are below the sleep thresholds
    /// </summary>
    /// <param name="dt">The time delta</param>
    /// <returns>True if the die is settled, false otherwise</returns>
    public bool IsSettled(float dt)
    {
        if (rb == null) return false;

        bool slowEnough =
            rb.linearVelocity.sqrMagnitude <= linearSleepThreshold * linearSleepThreshold &&
            rb.angularVelocity.sqrMagnitude <= angularSleepThreshold * angularSleepThreshold;

        settledTimer = slowEnough ? (settledTimer + dt) : 0f;
        return settledTimer >= settleTimeRequired;
    }

    /// <summary>
    /// Gets the top face value by finding the face with the highest dot product with the gravity up
    /// </summary>
    /// <returns>The top face value</returns>
    public int GetTopFaceValue()
    {
        if (faces.Count == 0)
        {
            RebuildFaceCache();
            if (faces.Count == 0)
            {
                Debug.LogWarning($"[{nameof(Dice)}] No DieFace markers found under {name}.");
                return -1;
            }
        }

        // get the gravity up vector for custom gravity
        Vector3 upRef = GetGravityUp();

        int bestValue = -1;
        float bestDot = float.NegativeInfinity;

        foreach (DieFace face in faces)
        {
            // Convention: face marker's local +Y points outward from the face.
            float dot = Vector3.Dot(face.transform.up, upRef);
            if (dot > bestDot)
            {
                bestDot = dot;
                bestValue = face.value;
            }
        }

        return bestValue;
    }

    /// <summary>
    /// Gets the gravity up vector for custom gravity
    /// </summary>
    /// <returns>The gravity up vector</returns>
    public static Vector3 GetGravityUp()
    {
        return Physics.gravity.sqrMagnitude > 0.0001f
            ? (-Physics.gravity).normalized
            : Vector3.up;
    }

    /// <summary>
    /// Gets the gravity scale by dividing the gravity magnitude by the baseline
    /// </summary>
    /// <param name="baseline">The baseline gravity</param>
    /// <returns>The gravity scale</returns>
    public static float GetGravityScale(float baseline = 9.81f)
    {
        if (baseline <= 0f) baseline = 9.81f;
        return Physics.gravity.magnitude / baseline;
    }

#if UNITY_EDITOR
    [ContextMenu("Auto Generate D20 Face Markers")]
    /// <summary>
    /// Auto generates the face markers for the die in the editor
    /// </summary>
    private void AutoGenerateD20FaceMarkers()
    {
        if (meshRoot == null)
        {
            Transform meshByName = transform.Find("Mesh");
            meshRoot = meshByName != null ? meshByName : transform;
        }

        MeshFilter mf = meshRoot.GetComponentInChildren<MeshFilter>(true);
        if (mf == null || mf.sharedMesh == null)
        {
            Debug.LogError($"[{nameof(Dice)}] No MeshFilter/sharedMesh found under meshRoot.");
            return;
        }

        if (facesRoot == null)
        {
            Transform existing = transform.Find("Faces");
            if (existing != null)
            {
                facesRoot = existing;
            }
            else
            {
                GameObject go = new GameObject("Faces");
                go.transform.SetParent(transform, false);
                facesRoot = go.transform;
            }
        }

        if (clearExistingFaces)
        {
            var children = new List<GameObject>();
            for (int i = 0; i < facesRoot.childCount; i++)
            {
                children.Add(facesRoot.GetChild(i).gameObject);
            }

            foreach (GameObject child in children)
            {
                UnityEditor.Undo.DestroyObjectImmediate(child);
            }
        }

        Mesh mesh = mf.sharedMesh;
        Vector3[] verts = mesh.vertices;
        int[] tris = mesh.triangles;
        Transform meshTx = mf.transform;

        var clusters = new List<FaceCluster>();

        for (int i = 0; i < tris.Length; i += 3)
        {
            Vector3 w0 = meshTx.TransformPoint(verts[tris[i]]);
            Vector3 w1 = meshTx.TransformPoint(verts[tris[i + 1]]);
            Vector3 w2 = meshTx.TransformPoint(verts[tris[i + 2]]);

            Vector3 n = Vector3.Cross(w1 - w0, w2 - w0);
            float mag = n.magnitude;
            if (mag < 0.000001f) continue;

            n /= mag;
            Vector3 center = (w0 + w1 + w2) / 3f;
            float area = mag * 0.5f;

            bool merged = false;
            for (int c = 0; c < clusters.Count; c++)
            {
                // Use abs(dot) to merge same plane with opposite winding.
                if (Mathf.Abs(Vector3.Dot(clusters[c].Normal, n)) >= normalDotThreshold)
                {
                    clusters[c].Add(center, n, area);
                    merged = true;
                    break;
                }
            }

            if (!merged)
            {
                var fc = new FaceCluster();
                fc.Add(center, n, area);
                clusters.Add(fc);
            }
        }

        clusters = clusters
            .OrderByDescending(c => c.Weight)
            .Take(20)
            .ToList();

        if (clusters.Count != 20)
        {
            Debug.LogWarning($"[{nameof(Dice)}] Found {clusters.Count} clusters (expected 20). Adjust normalDotThreshold.");
        }

        // Deterministic ordering so names don't jump each run.
        clusters = clusters
            .OrderByDescending(c => c.Normal.y)
            .ThenByDescending(c => c.Normal.z)
            .ThenByDescending(c => c.Normal.x)
            .ToList();

        for (int i = 0; i < clusters.Count; i++)
        {
            GameObject marker = new GameObject($"Face_{i + 1}");
            UnityEditor.Undo.RegisterCreatedObjectUndo(marker, "Create Die Face Marker");

            marker.transform.SetParent(facesRoot, true);
            marker.transform.position = clusters[i].Center;
            marker.transform.rotation = Quaternion.FromToRotation(Vector3.up, clusters[i].Normal);

            DieFace dieFace = marker.AddComponent<DieFace>();
            dieFace.value = i + 1; // Adjust manually if your numbering map differs.
        }

        RebuildFaceCache();
        Debug.Log($"[{nameof(Dice)}] Generated {faces.Count} face markers.");
    }

    private class FaceCluster
    {
        private Vector3 normalAccum;
        private Vector3 centerAccum;
        private float weightAccum;

        public float Weight => weightAccum;
        public Vector3 Normal => normalAccum.normalized;
        public Vector3 Center => weightAccum > 0f ? centerAccum / weightAccum : Vector3.zero;

        public void Add(Vector3 center, Vector3 normal, float weight)
        {
            if (weight <= 0f) return;

            // Keep normal direction consistent in cluster.
            if (normalAccum.sqrMagnitude > 0.0001f && Vector3.Dot(normalAccum, normal) < 0f)
            {
                normal = -normal;
            }

            normalAccum += normal * weight;
            centerAccum += center * weight;
            weightAccum += weight;
        }
    }
#endif
}